// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProtoDesc {
    #[prost(bytes="vec", optional, tag="1")]
    pub desc: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(message, repeated, tag="2")]
    pub dependencies: ::prost::alloc::vec::Vec<ProtoDesc>,
}
// @@protoc_insertion_point(module)
